apiVersion: v1
data:
    dynamic-scaling: "true"
    backend-server-slots-increment: "42"
    dns-resolvers: |
        kubernetes=10.96.0.10:53
        other=10.96.0.11:53,10.96.0.12:53
        another=10.96.0.13,10.96.0.14
kind: ConfigMap
metadata:
  name: haproxy-configmap
