apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
  annotations:
    ingress.kubernetes.io/use-resolver: kubernetes
spec:
  clusterIP: None
  selector:
    name: web
  ports:
   - port: 8080
     targetPort: 8080
