blank_issues_enabled: true
contact_links:
- name: Slack
  url: http://jitec.com.br/slack/
  about: Chat and get support from other HAProxy Ingress users.
- name: Mailing List
  url: https://groups.google.com/forum/#!forum/haproxy-ingress
  about: Ask questions and follow announcements. Post via `haproxy-ingress@groups.google.com` mail address without being subscribed.
- name: Stack Overflow
  url: https://stackoverflow.com/questions/tagged/haproxy-ingress
  about: Practical questions and curated answers.
